# Generated by Django 2.2.1 on 2019-06-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='grouplessons',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lesson_access',
            field=models.BooleanField(default=False),
        ),
    ]
