# Generated by Django 2.2.1 on 2019-06-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190606_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='display_time',
            field=models.TimeField(null=True),
        ),
    ]
