# Generated by Django 2.2.1 on 2019-06-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190614_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
