# Generated by Django 2.2.1 on 2019-06-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='color',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.AddField(
            model_name='stock',
            name='document',
            field=models.FileField(default=None, upload_to='static/main/shop/'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
