# Generated by Django 2.2.1 on 2019-06-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190614_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(through='main.CartItems', to='main.Stock'),
        ),
    ]
