# Generated by Django 2.2.1 on 2019-06-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190614_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
