# Generated by Django 2.2.1 on 2019-06-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190611_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='document',
            field=models.ImageField(default=None, upload_to='media/images/'),
        ),
    ]
