# Generated by Django 2.2.1 on 2019-06-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190611_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='available',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
