# Generated by Django 2.2.1 on 2019-06-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190611_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='color',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
