# Generated by Django 2.2.1 on 2019-06-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190619_0926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
