# Generated by Django 2.2.1 on 2019-06-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_stock_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='display_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
    ]
