# Generated by Django 2.2.1 on 2019-06-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190611_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('visual', models.ImageField(default=None, upload_to='images/')),
                ('price_month', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('group', models.BooleanField(default=None)),
            ],
        ),
    ]
