# Generated by Django 2.2.1 on 2019-06-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_user_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
