# Generated by Django 2.2.1 on 2019-06-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190623_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
